### PR TITLE
ENH enable py3

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds python 3.X and modernizes some of the recipe parts.

### CODE REVIEW

**Comment by beckermr** [comment]
@JohannesBuchner I added python 3. All of the tests pass. I am going to rerender the feedstock one more time, but this is ready to merge.

@conda-forge-admin, please rerender
@conda-forge-admin, please update team

**Comment by beckermr** [comment]
@conda-forge-admin, please update team

**Comment by beckermr** [comment]
Ping on this PR @JohannesBuchner

**Comment by JohannesBuchner** [comment]
Not sure what I am supposed to do here, @giacomov is likely more competent.

**Comment by beckermr** [comment]
Hi the megre button!

**Comment by beckermr** [comment]
To be more specific, once you merge the PR, conda-forge will automatically build the recipes and upload them to the cloud.

**Comment by beckermr** [comment]
Ohhhh weird. Usually all of the maintainers listed on the recipe have write access. It appears only @giacomov is a member of the [team](https://github.com/orgs/conda-forge/teams/pymultinest/members) so indeed @giacomov will have to press the merge button. 

The conda-forge admin robot should update the team when this PR is merged.

Thanks for the help @JohannesBuchner!

**Comment by beckermr** [comment]
Ping @giacomov! When you have a chance! :)

**Comment by giacomov** [comment]
Thanks for the contribution!

**Pull request merged**
